# experiment setup
setup:
  seed: 42
  device: 0
  base_save_dir: ./results/synthetic
  about: unlearn-eps_multiplier

# exact surrogate dataset initialization
data:
  exact_dataset: gaussian # it could be either gaussian, ball or hypercube
  surrogate_dataset: gaussian # it could be either gaussian, ball or hypercube
  num_samples: 15000
  dim: 50
  num_class: 10
  off_cov: 0.05

# training related
train:
  test_ratio: 0.1
  batch_size: 512
  lambda: 0.01
  model:
    type: mlp
    hidden_sizes: none
    activation: none
    bias: false
  lr: 0.001
  num_epochs: 300

unlearn:
  # unlearning related
  forget_ratio: 0.1
  # noise related
  eps_multiplier: 5
  eps_power: 3
  delta: 1
  smooth: 1
  sc: 1.01
  lip: 1
  hlip: 1
  surr: true
  known: true
  linear: true
  parallel: false
  cov: false
  alpha: 1
