data:
  dim: 50
  exact_dataset: gaussian
  num_class: 10
  num_samples: 15000
  off_cov: 0.05
  surrogate_dataset: gaussian
setup:
  about: train-model-hidden_sizes
  base_save_dir: ./results/synthetic/model/hsizes
  device: 3
  seed: 42
train:
  batch_size: 512
  lambda: 0.01
  lr: 0.001
  model:
    activation: relu
    bias: false
    hidden_sizes:
    - 20
    type: mlp
  num_epochs: 300
  test_ratio: 0.1
unlearn:
  alpha: 1
  conjugate: true
  cov: false
  delta: 1
  eps_multiplier: 5
  eps_power: 3
  forget_ratio: 0.1
  hlip: 1
  known: true
  linear: false
  lip: 1
  parallel: false
  sc: 1.01
  smooth: 1
  surr: true
