data:
  dim:
  - 512
  dirichlet: 10
  exact_dataset: stanforddogs-act
  num_class: 120
  save_path: none
  ssave_path: none
  stest_path: none
  strain_path: none
  surrogate_dataset: none
  test_path: ./data/stanforddogs-extracted-features/linear_test.pth
  train_path: ./data/stanforddogs-extracted-features/linear_train.pth
langevin:
  batch_size: 128
  input_range:
  - -3
  - 3
  input_size:
  - 512
  max_iter: 4000
  num_samples: 1000
  step_size: 0.02
setup:
  about: unlearn-delta
  base_save_dir: ./results/real/stanforddogs/delta
  device: 0
  seed: 42
train:
  batch_size: 128
  lambda: 0.01
  lr: 0.001
  model:
    mode: linear
    type: resnet18
  num_epochs: 10
unlearn:
  alpha: 1
  conjugate: true
  cov: false
  delta: 0.2
  eps_multiplier: 5
  eps_power: 3
  forget_ratio: 0.1
  hlip: 1
  known: true
  linear: false
  lip: 1
  parallel: false
  sc: 1.01
  smooth: 1
  surr: true
