data:
  dim: 512
  dirichlet: 10
  exact_dataset: cifar10-act
  num_class: 10
  save_path: none
  ssave_path: none
  stest_path: none
  strain_path: none
  surrogate_dataset: none
  test_path: /home/umityigitbsrn/Desktop/umityigitbsrn/certified-unlearning-surr-data/data/cifar10_linear_resnet18_test.pth
  train_path: /home/umityigitbsrn/Desktop/umityigitbsrn/certified-unlearning-surr-data/data/cifar10_linear_resnet18_train.pth
langevin:
  batch_size: 256
  input_range:
  - 0
  - 12
  input_size:
  - 512
  max_iter: 2000
  num_samples: 500
  step_size: 0.02
setup:
  about: unlearn-delta
  base_save_dir: ./results/real/delta/cifar10
  device: 0
  seed: 42
train:
  batch_size: 128
  lambda: 0.01
  lr: 0.001
  model:
    activation: none
    bias: false
    hidden_sizes: none
    type: mlp
  num_epochs: 50
unlearn:
  cov: true
  delta: 0.4
  eps_multiplier: 5
  eps_power: 3
  forget_ratio: 0.1
  hlip: 1
  known: true
  linear: true
  lip: 1
  parallel: false
  sc: 1.01
  smooth: 1
  surr: true
