data:
  dim: 50
  exact_dataset: gaussian
  num_class: 10
  num_samples: 15000
  off_cov: 0.02
  surrogate_dataset: gaussian
setup:
  base_save_dir: ./results/synthetic/offcov
  device: 0
  seed: 42
train:
  batch_size: 512
  lambda: 0.001
  lr: 0.001
  model:
    activation: none
    bias: false
    hidden_sizes: none
    type: mlp
  num_epochs: 300
  test_ratio: 0.1
unlearn:
  delta: 1
  eps_multiplier: 5
  eps_power: 3
  forget_ratio: 0.1
  hlip: 1
  known: true
  lip: 1
  sc: 1
  smooth: 1
  surr: true
