# experiment setup
setup:
  seed: 42
  device: 1
  base_save_dir: ./results/real
  about: data-exact_dataset

# exact surrogate dataset initialization
data:
  exact_dataset: cifar10-act
  surrogate_dataset: none
  dim:
    - 512
  num_class: 10
  dirichlet: 10
  train_path: ./data/cifar10-extracted-features/linear_train.pth
  test_path: ./data/cifar10-extracted-features/linear_test.pth
  save_path: none
  strain_path: none
  stest_path: none
  ssave_path: none

# training related
train:
  batch_size: 128
  lambda: 0.01
  model:
    type: resnet18
    mode: linear
  lr: 0.001
  num_epochs: 10

langevin:
  num_samples: 1000
  input_size:
    - 512
  batch_size: 128
  input_range:
    - -3
    - 3
  max_iter: 4000
  step_size: 0.02

unlearn:
  # unlearning related
  forget_ratio: 0.1
  # noise related
  eps_multiplier: 5
  eps_power: 3
  delta: 1
  smooth: 1
  sc: 1.01
  lip: 1
  hlip: 1
  surr: true
  known: true
  linear: false
  parallel: false
  cov: false
  alpha: 1
  conjugate: true
