data:
  dim: 50
  exact_dataset: gaussian
  num_class: 10
  num_samples: 15000
  off_cov: 0.01
  surrogate_dataset: gaussian
setup:
  about: data-off_cov
  base_save_dir: ./results/synthreal/offcov
  device: 0
  seed: 42
train:
  batch_size: 512
  lambda: 0.01
  lr: 0.001
  model:
    activation: none
    bias: false
    hidden_sizes: none
    type: mlp
  num_epochs: 300
  test_ratio: 0.1
unlearn:
  alpha: 1
  conjugate: true
  cov: false
  delta: 1
  eps_multiplier: 5
  eps_power: 3
  forget_ratio: 0.1
  hlip: 1
  known: true
  linear: false
  lip: 1
  parallel: false
  sc: 1.01
  smooth: 1
  surr: true
langevin:
  batch_size: 128
  input_range:
  - -3
  - 3
  input_size:
  - 512
  max_iter: 4000
  num_samples: 1000
  step_size: 0.02
